export type StringKey = 
  | 'home'
  | 'regional'
  | 'international'
  | 'latestNews'
  | 'topNews'
  | 'readMore'
  | 'viewAll'
  | 'footerText'
  | 'copyright'
  | 'navigation'
  | 'contact'
  | 'followUs'
  | 'by'
  | 'views'
  | 'likes';
