name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
main_v3(Angular-18)
      - production_deployment

      - main

 main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
 main_v3(Angular-18)
      - uses: actions/checkout@v4
      - run: ng build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the desired Node.js version here

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies and build
        run: |
          npm install
          ng build --configuration=production

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NETICHARITHRA_NCMEDIA }}'
          projectId: neticharithra-ncmedia
          channelId: live
